name: Python application

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      onefile:
        description: "File to be built"
        default: mlLevel
    
jobs:
  setup-params:
    runs-on: ubuntu-latest
    outputs:
      onefile: ${{ steps.params.outputs.onefile }}
    steps:
    - name: Set up parameters
      id: params
      run: |
        echo "onefile=${{ inputs.onefile }}" >> $GITHUB_OUTPUT

  build:
    needs: setup-params
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build app
      run: |
        pyinstaller --onefile ${{ needs.setup-params.outputs.onefile }}.py

    - name: Upload app to artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ needs.setup-params.outputs.onefile }}-${{ matrix.os }}
        path: dist/
   
